CREATE DATABASE privchat;  
USE privchat;  

CREATE TABLE users (  
    id INT AUTO_INCREMENT PRIMARY KEY,  
    fullname VARCHAR(255) NOT NULL,  
    email VARCHAR(255) UNIQUE NOT NULL,  
    username VARCHAR(100) UNIQUE NOT NULL,  
    password VARCHAR(255) NOT NULL,  
    mobile VARCHAR(15) UNIQUE NOT NULL,  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);  
